import { useMemo, useState } from 'react'
import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import ExcelJS from 'exceljs'
import type { Recharge } from './data'

type Occurrence = { id:number; employeeId:number; date:string; endDate?:string; type:'Falta'|'Atestado'|'Atraso'|'Aviso'; hours?:number; minutes?:number; days?:number; note?:string }
type ReportType = 'Completo'|'Atrasos'|'Faltas'|'Atestados'|'Período de experiência'|'Cumprindo aviso'|'Funcionários desligados'|'Dados dos funcionários'
type ReportRow = { values:(string|number)[] }

const types:ReportType[]=['Completo','Atrasos','Faltas','Atestados','Período de experiência','Cumprindo aviso','Funcionários desligados','Dados dos funcionários']
const format=(value?:string)=>value?new Date(value+'T12:00:00').toLocaleDateString('pt-BR'):'-'
const addDays=(value:string,days:number)=>{const date=new Date(value+'T12:00:00');date.setDate(date.getDate()+days);return date}
const monthLabel=(value:string)=>{const label=new Date(`${value}-01T12:00:00`).toLocaleDateString('pt-BR',{month:'long',year:'numeric'});return label.charAt(0).toUpperCase()+label.slice(1)}

export default function HRReports({employees,occurrences}:{employees:Recharge[];occurrences:Occurrence[]}){
 const now=new Date(),[month,setMonth]=useState(`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`),[store,setStore]=useState('Todas'),[type,setType]=useState<ReportType>('Completo');
 const stores=[...new Set(employees.map(employee=>employee.store))].sort();
 const result=useMemo(()=>{
  const selectedEmployees=employees.filter(employee=>store==='Todas'||employee.store===store),active=selectedEmployees.filter(employee=>employee.terminationDate?new Date(employee.terminationDate+'T12:00:00')>now:employee.active!==false&&employee.employmentStatus!=='Desligado'),activeIds=new Set(active.map(employee=>employee.id)),map=new Map(employees.map(employee=>[employee.id,employee])),monthOccurrences=occurrences.filter(item=>item.date.startsWith(month)&&activeIds.has(item.employeeId));
  if(type==='Dados dos funcionários')return {headers:['Nome completo','CPF','Nascimento','Admissão','Cargo / setor','Loja','Situação','Carteira','Benefício'],rows:active.map(employee=>({values:[employee.employee,employee.cpf||'-',format(employee.birthDate),format(employee.hiredAt),employee.role,employee.store,employee.employmentStatus||'Ativo',employee.formalEmployment===false?'Sem carteira':'Assinada',employee.receivesCostAssistance?'Ajuda de custo':employee.receivesTransit===false?'Sem vale-transporte':'Vale-transporte']}))};
  if(type==='Funcionários desligados'){const list=selectedEmployees.filter(employee=>employee.terminationDate?.startsWith(month)||((employee.active===false||employee.employmentStatus==='Desligado')&&!employee.terminationDate));return {headers:['Nome completo','CPF','Cargo / setor','Loja','Admissão','Desligamento','Acerto até'],rows:list.map(employee=>({values:[employee.employee,employee.cpf||'-',employee.role,employee.store,format(employee.hiredAt),format(employee.terminationDate),employee.terminationDate?addDays(employee.terminationDate,10).toLocaleDateString('pt-BR'):'Não informado']}))}}
  if(type==='Período de experiência'){const start=new Date(`${month}-01T00:00:00`),end=new Date(start.getFullYear(),start.getMonth()+1,0,23,59,59);const list=active.filter(employee=>{if(!employee.hiredAt)return false;const admission=new Date(employee.hiredAt+'T12:00:00'),finish=addDays(employee.hiredAt,89);return admission<=end&&finish>=start});return {headers:['Funcionário','CPF','Cargo / setor','Loja','Admissão','Fim da experiência','Dias restantes'],rows:list.map(employee=>{const finish=addDays(employee.hiredAt!,89),days=Math.ceil((finish.getTime()-now.getTime())/86400000);return {values:[employee.employee,employee.cpf||'-',employee.role,employee.store,format(employee.hiredAt),finish.toLocaleDateString('pt-BR'),days>=0?days:'Encerrada']}})} }
  if(type==='Cumprindo aviso'){const start=new Date(`${month}-01T00:00:00`),end=new Date(start.getFullYear(),start.getMonth()+1,0,23,59,59),list=active.filter(employee=>employee.noticeStart&&employee.noticeEnd&&new Date(employee.noticeStart+'T12:00:00')<=end&&new Date(employee.noticeEnd+'T12:00:00')>=start);return {headers:['Funcionário','CPF','Cargo / setor','Loja','Início do aviso','Término do aviso','Dias restantes'],rows:list.map(employee=>{const finish=new Date(employee.noticeEnd+'T12:00:00'),days=Math.ceil((finish.getTime()-now.getTime())/86400000);return {values:[employee.employee,employee.cpf||'-',employee.role,employee.store,format(employee.noticeStart),format(employee.noticeEnd),days>=0?days:'Encerrado']}})} }
  const wanted=type==='Atrasos'?'Atraso':type==='Faltas'?'Falta':type==='Atestados'?'Atestado':null,list=wanted?monthOccurrences.filter(item=>item.type===wanted):monthOccurrences;
  return {headers:['Data','Funcionário','Loja','Tipo','Detalhe'],rows:list.map(item=>{const employee=map.get(item.employeeId),detail=item.type==='Atestado'?`${item.days||1} dia(s)`:item.type==='Aviso'?`Até ${format(item.endDate)}`:item.type==='Falta'?'Falta registrada nesta data':`${item.hours||0}h ${item.minutes||0}min`;return {values:[format(item.date),employee?.employee||'Funcionário removido',employee?.store||'-',item.type,detail]}})};
 },[employees,occurrences,month,store,type]);
 const exportPdf=async()=>{const doc=new jsPDF({orientation:'landscape'}),logo=await fetch('/sacolao-abc-logo.png?v=4').then(r=>r.blob()).then(blob=>new Promise<string>(resolve=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.readAsDataURL(blob)}));doc.setFillColor(38,38,38);doc.rect(0,0,297,34,'F');doc.addImage(logo,'PNG',12,5,27,23);doc.setTextColor(255,255,255);doc.setFontSize(18);doc.text(`Relatório de RH — ${type}`,45,15);doc.setFontSize(9);doc.text(`${monthLabel(month)} | ${store==='Todas'?'Todas as lojas':store} | ${result.rows.length} registro(s)`,45,23);autoTable(doc,{startY:41,head:[result.headers],body:result.rows.map(row=>row.values),headStyles:{fillColor:[38,38,38]},alternateRowStyles:{fillColor:[244,244,244]},styles:{fontSize:8,cellPadding:2.5}});doc.save(`rh-${type.toLowerCase().replaceAll(' ','-')}-${month}.pdf`)};
 const exportExcel=async()=>{const wb=new ExcelJS.Workbook(),ws=wb.addWorksheet('Relatório RH',{views:[{state:'frozen',ySplit:5,showGridLines:false}]});const logo=await fetch('/sacolao-abc-logo.png?v=4').then(r=>r.arrayBuffer()),id=wb.addImage({buffer:logo as never,extension:'png'});ws.addImage(id,{tl:{col:.2,row:.1},ext:{width:145,height:65}});ws.mergeCells(1,3,2,Math.max(7,result.headers.length));ws.getCell('C1').value=`RELATÓRIO DE RH — ${type.toUpperCase()}`;ws.getCell('C1').font={size:16,bold:true,color:{argb:'FF262626'}};ws.getCell('C3').value=`${monthLabel(month)} | Loja: ${store}`;ws.addRow([]);ws.addRow(result.headers);result.rows.forEach(row=>ws.addRow(row.values));ws.getRow(5).eachCell(cell=>{cell.font={bold:true,color:{argb:'FFFFFFFF'}};cell.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF262626'}}});result.headers.forEach((_,index)=>ws.getColumn(index+1).width=index===0?28:20);const bytes=await wb.xlsx.writeBuffer(),url=URL.createObjectURL(new Blob([bytes]));const anchor=document.createElement('a');anchor.href=url;anchor.download=`rh-${type.toLowerCase().replaceAll(' ','-')}-${month}.xlsx`;anchor.click();URL.revokeObjectURL(url)};
 return <main className="fade-in p-4 sm:p-7"><div><h2 className="text-2xl font-bold text-slate-900">Relatórios de Recursos Humanos</h2><p className="mt-1 text-sm text-slate-500">Selecione um relatório para visualizar e exportar.</p></div><div className="mt-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="grid gap-3 md:grid-cols-3 xl:grid-cols-5"><label className="text-xs font-semibold text-slate-600">Tipo de relatório<select value={type} onChange={event=>setType(event.target.value as ReportType)} className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-2.5">{types.map(item=><option key={item}>{item}</option>)}</select></label><label className="text-xs font-semibold text-slate-600">Mês<input type="month" value={month} onChange={event=>setMonth(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-2.5"/></label><label className="text-xs font-semibold text-slate-600">Loja<select value={store} onChange={event=>setStore(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-2.5"><option>Todas</option>{stores.map(item=><option key={item}>{item}</option>)}</select></label><button onClick={exportPdf} className="self-end rounded-xl border border-red-300 px-4 py-2.5 text-sm font-semibold text-red-600">Gerar PDF</button><button onClick={exportExcel} className="self-end rounded-xl bg-[#262626] px-4 py-2.5 text-sm font-semibold text-white">Gerar Excel</button></div></div><div className="mt-5 overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4"><h3 className="font-bold">{type}</h3><p className="text-xs text-slate-400">{result.rows.length} registro(s) em {monthLabel(month)}</p></div><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-400"><tr>{result.headers.map(header=><th key={header} className="px-4 py-3">{header}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{result.rows.map((row,index)=><tr key={index}>{row.values.map((value,column)=><td key={column} className="px-4 py-3">{value}</td>)}</tr>)}{!result.rows.length&&<tr><td colSpan={result.headers.length} className="py-12 text-center text-slate-400">Nenhum registro para os filtros selecionados.</td></tr>}</tbody></table></div></main>
}
